### ISSUE TITLE
Handle Concurrency Errors in Lambda deployments

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-deploy#83]
```
Unable to deploy Lambda function: The function could not be updated due to a concurrent update operation. { ResourceConflictException: The function could not be updated due to a concurrent update operation.
    at deserializeAws_restJson1UpdateFunctionConfigurationCommandError (/home/circleci/repo/node_modules/@aws-sdk/client-lambda/dist/cjs/protocols/Aws_restJson1.js:7670:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ResourceConflictException',
  '$fault': 'client',
  '$metadata':
   { httpStatusCode: 409,
     requestId: '9ce0bb78-d6c9-4e26-8803-a037ffccf10c',
     extendedRequestId: undefined,
     cfId: undefined,
     attempts: 1,
     totalRetryDelay: 0 },
  Type: 'User' }
error: AmazonWebServices - The function could not be updated due to a concurrent update operation.
```

https://app.circleci.com/pipelines/github/adobe/helix-deploy/254/workflows/ef7cfa1c-2bf0-4993-9412-09cd672a44a0/jobs/230/steps

**Comment by tripodsan** [comment]
haven't seen this for a while... closing won't fix for now
